name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create credentials file from secret
        env:
          FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: echo "$FIREBASE_CREDS" > firebase_credentials.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cx_freeze lxml openpyxl Pillow ttkbootstrap requests firebase-admin bcrypt cryptography pytz pandas reportlab python-docx google-api-python-client google-auth-httplib2 google-auth-oauthlib

      # --- [NOVO PASSO] ---
      # Renomeia o .gitignore para que o cx_Freeze não o leia e ignore o arquivo de credenciais
      - name: Temporarily rename .gitignore
        run: mv .gitignore gitignore.bak

      - name: Build the application
        run: python Setup.py build

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: CustomsFlow-macOS-Build
          path: build/