name: Build macOS Application

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Create credentials files from secrets
        env:
          FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDENTIALS }}
          GDRIVE_CREDS: ${{ secrets.GOOGLE_DRIVE_CREDENTIALS }}
        run: |
          echo "$FIREBASE_CREDS" > firebase_credentials.json
          echo "$GDRIVE_CREDS" > google_drive_credentials.json

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade cx_freeze lxml openpyxl Pillow ttkbootstrap requests firebase-admin bcrypt cryptography pytz pandas reportlab python-docx google-api-python-client google-auth-httplib2 google-auth-oauthlib

      - name: Temporarily rename .gitignore
        run: mv .gitignore gitignore.bak

      # --- [CORRIGIDO] Comando de build alterado para o específico de macOS ---
      - name: Build the application for macOS
        run: python Setup.py bdist_mac

      - name: Upload macOS build artifact
        uses: actions/upload-artifact@v4
        with:
          name: CustomsFlow-macOS-Build
          # O resultado do bdist_mac fica em uma pasta diferente
          path: build/*.dmg